# The container name used for the run container
container-name-run : "pythonflaskbasicwdsqd-flask-run"
# The container name used for the tools container
container-name-tools : "pythonflaskbasicwdsqd-flask-tools"

# The project root on the host for the run container to mount to container-path-run
host-path-run : "."
# The project root on the host for the tools container to mount to container-path-tools
host-path-tools : "."

# The project root in the run container to mount to host-path-run
container-path-run : "/app"
# The project root in the tools container that will be mounted to host-path-tools
container-path-tools : "/app"

# The port mappings between the host and the container in the form [host:container]
container-port-map : "3000:3000"
# The port mappings between the host and the container for the debug port in the form [host:container]
container-port-map-debug : "5858:5858"


# The name for the dockerfile for the run container
dockerfile-run : "Dockerfile"
# The name for the dockerfile for the tools container
dockerfile-tools : "Dockerfile-tools"

# The name of image to create from dockerfile-run
image-name-run : "pythonflaskbasicwdsqd-flask-run"
# The name of image to create from dockerfile-tools
image-name-tools : "pythonflaskbasicwdsqd-flask-tools"

# The command to build the code and docker image for RUN
build-cmd-run : "npm run build; python manage.py build"
# The command to execute tests for the code in the tools container
test-cmd : "python manage.py test"
# The command to build the code and docker image for DEBUG
build-cmd-debug : "npm run build; python manage.py build"

# The command to run the code in the run container
run-cmd : ""
# The command to execute debug of the code in the tools container
debug-cmd : "python manage.py debug"
# The command to stop the code
stop-cmd : ""

# The relative path to the helm chart used for Kubernetes deployment
chart-path : "chart/pythonflaskbasicwdsqd"

# The IBM version of this configuration
version : "0.0.3"
ibm-generated-id : "12067418-c7f7-4762-a0e1-26ab687032d4"
ibm-cloud-app-id : "6749b4c8-6912-409c-829d-cae654151ee3"
credentials-filepath : "credentials.json, localdev-config.json, server/localdev-config.json"